
# 建立一維NumPy Arrays

可以經由傳送串列(list)或元組(tuple)給`np.array`即可建立一維陣列.

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array((1, 2, 3, 4))
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


也可以透過`np.arange`建立一維NumPy array，其使用方式類似Python標準庫中的`range`，如下面實例可在3-30(包含3但不含30)間隔3建立一維陣列。

In [2]:
c = np.arange(3, 30, 3)
print(c)

[ 3  6  9 12 15 18 21 24 27]


`np.linspace` 則可建立一個間隔相同的陣列，如下面實例可在0-10間建立有5個元素的陣列，間隔相同(均為2.5)

In [3]:
pi_steps = np.linspace(0, 10, 5)
print(pi_steps)

[ 0.   2.5  5.   7.5 10. ]


## 一維陣列以索引(Index)存取元素

In [4]:
print(c)
print(c[0])  # 取得在index位置0的元素
print(c[1])  # 取得在index位置1的元素
print(c[2:6])  # 取得在index位置2-5(包含2但不含6)的子陣列(subarray)
print(c[1:-1:2])  # 取得陣列c中index位置1,3,5,..(各間隔1個元素來選取)的子陣列

[ 3  6  9 12 15 18 21 24 27]
3
6
[ 9 12 15 18]
[ 6 12 18 24]


# 多維陣列(multi-dimensional arrays)
可以經由直接傳送多維串列(list)給np.array即可建立多維陣列，接著可以透過`np.shape`取得其外形(shape)。如下面實例中two_dim為2X3陣列(2列3行)；three_dim則為2X3X4陣列：

In [6]:
two_dim = np.array([[ 1,  2,  3,  4],
                    [ 5,  6,  7,  8],
                    [ 9, 10, 11, 12]])
three_dim = np.array([[[ 1,  2,  3,  4],
                       [ 5,  6,  7,  8],
                       [ 9, 10, 11, 12]],
                      [[13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]]])
print(two_dim.shape)
print(three_dim.shape)

(3, 4)
(2, 3, 4)


也可以建立一維陣列，接著利用numpy的`reshape`可以轉為所需要的各種外形。如下面實例中，a原為1X25陣列，可以reshape為5X5陣列；也可以直接建立陣列後呼叫`reshape`方法轉為3X4陣列。

In [7]:
a = np.arange(1, 26).reshape(5, 5)
print(a.shape)
print(a)
print(a[2, 4])
print(a.shape)
np.arange(12).reshape(3, 4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
15
(5, 5)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 多維陣列以Index存取元素


In [9]:
a = np.arange(1, 26).reshape(5, 5)
print(a)
print(a[0, 1:4])  # 獲取由row 0(第0個橫列)中第1個-第3個元素(不含第4個)產生的一維子陣列
print(a[1:4, 0])  # 獲取由column 0(第0個直行)中第1個-第3個元素(不含第4個)產生的一維子陣列
print(a[::2,::2])  # 獲取一個二維陣列，由橫列與直行中隔個元素產生(0、2、4列與0、2、4行，也就是(0,0),(0,2),(0,4),(2,0),(2,2),(4),(4,0),(4,2),(4,4等9個元素)
print(a[:, 1])  # 獲取由整個column 1(第1個直行)中元素產生的一維子陣列

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[2 3 4]
[ 6 11 16]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[ 2  7 12 17 22]


In [14]:
a = np.arange(0, 60).reshape((4, 3, 5))
print("陣列a\n",a)

print("a[0, 1, 2]=",a[0, 1, 2])  # 存取a[0][1][2]
print("a[:,2]=\n",a[:,2])  # 產生由內部二維陣列中row 2(第三個橫列)組成的串列
print("a[:,:,2]=\n",a[:,:,2])  # 產生由內部二維陣列中column 2(第三個直行)組成的串列
print("a[::2,::2,::2]=\n",a[::2,::2,::2])  # 產生一個三維陣列，由橫列與直行中隔個元素產生

陣列a
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
a[0, 1, 2]= 7
a[:,2]=
 [[10 11 12 13 14]
 [25 26 27 28 29]
 [40 41 42 43 44]
 [55 56 57 58 59]]
a[:,:,2]=
 [[ 2  7 12]
 [17 22 27]
 [32 37 42]
 [47 52 57]]
a[::2,::2,::2]=
 [[[ 0  2  4]
  [10 12 14]]

 [[30 32 34]
  [40 42 44]]]
