# 陣列排序(Sorting Arrays)

本範例介紹與NumPy陣列中的值排序相關的演算法，例如，一個簡單的選擇排序重複從列表中查找最小值，並進行交換直到列表排序。 我們可以在幾行Python中完成程式編寫：

In [1]:
import numpy as np
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x
x = np.array([2, 1, 4, 6, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5, 6])

## 在NumPy中快速排序方式：``np.sort``和``np.argsort``

儘管Python內建了``sort``和``sorted``函數來處理串列，但效率較差。預設情況下，``np.sort``使用* quicksort *算法，但* mergesort *和* heapsort *也可用。 要在不修改輸入的情況下返回陣列的排序版本，可以使用``np.sort``：

In [2]:
x = np.array([2, 1, 4, 6, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5, 6])

如果您希望就地對陣列進行排序，則可以使用陣列的``sort``方法：

In [3]:
x.sort()
print(x)

[1 2 3 4 5 6]


相關的函數是``argsort``，它返回已排序元素的* indices *：

In [4]:
x = np.array([2, 1, 4, 6, 3, 5])
i = np.argsort(x)
print(i)

[1 0 4 2 5 3]


此結果的第一個元素給出最小元素的索引，第二個值給出第二個最小元素的索引，依此類推。如果需要，可以通過花式索引使用這些索引建構排序陣列：

In [5]:
x[i]

array([1, 2, 3, 4, 5, 6])

### 經由列或行排序

NumPy排序演算法的一個有用特性是能夠使用``axis``參數對多維陣列的特定行或列進行排序。 例如：

In [6]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [7]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [8]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## 部分排序：分區

有時我們對排序整個陣列不感興趣，但只想在陣列中找到* k *最小值。 NumPy在``np.partition``函數中提供了這個功能。 ``np.partition``取一個陣列和一個數字* K *; 結果是一個新陣列，在分區左邊有最小的* K *值，剩下的值按任意順序在右邊：

In [9]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 4)

array([2, 1, 3, 4, 5, 6, 7])

請注意，結果陣列中的前四個值是陣列中的最小四個值，其餘陣列位置包含其餘值。
在這兩個分區中，元素具有任意順序。與排序類似，我們可以沿多維陣列的任意軸進行分區：

In [10]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

結果是一個陣列，其中每列中的前兩個元素為該列中的最小值，其餘值填充剩餘的元素。